(() => {
  'use strict';
  const REPO='LeszekSladkowski/CRM-SWIATLOWOD-EU';
  const API='https://api.github.com/repos/'+REPO;
  const $=s=>document.querySelector(s);
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const lang=localStorage.getItem('crm.language')||'pl';
  const L={
    pl:{ready:'Gotowy do sprawdzenia aktualizacji',smooth:'Wskaźnik postępu działa płynnie od 0 do 100%',checking:'Sprawdzanie połączenia z Internetem...',version:'Odczyt wersji zainstalowanej...',repo:'Sprawdzanie najnowszej wersji w GitHub...',deploy:'Kontrola wdrożenia GitHub Pages...',worker:'Kontrola mechanizmu aktualizacji przeglądarki...',cache:'Kontrola pamięci podręcznej...',done:'Aktualizacja i kontrola zakończona',ok:'WSZYSTKO OK',need:'AKTUALIZACJA',offline:'BRAK INTERNETU',browser:'PRZEGLĄDARKA',pwa:'PWA',auto:'AUTOMATYCZNE',manual:'RĘCZNE',stepReady:'SYSTEM GOTOWY',waiting:'Oczekiwanie na rozpoczęcie procesu',stepNet:'POŁĄCZENIE Z SIECIĄ',stepVersion:'WERSJA APLIKACJI',stepRepo:'NAJNOWSZY MAIN',stepDeploy:'DEPLOYMENT',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCES ZAKOŃCZONY',sync:'Ostatnia',clearing:'Czyszczenie pamięci podręcznej...',cleared:'Pamięć podręczna została wyczyszczona',versionInfo:'INFORMACJE O WERSJI'},
    en:{ready:'Ready to check for updates',smooth:'Progress indicator runs smoothly from 0 to 100%',checking:'Checking Internet connection...',version:'Reading installed version...',repo:'Checking latest GitHub version...',deploy:'Checking GitHub Pages deployment...',worker:'Checking browser update mechanism...',cache:'Checking cache...',done:'Update check completed',ok:'ALL OK',need:'UPDATE AVAILABLE',offline:'NO INTERNET',browser:'BROWSER',pwa:'PWA',auto:'AUTOMATIC',manual:'MANUAL',stepReady:'SYSTEM READY',waiting:'Waiting to start',stepNet:'NETWORK',stepVersion:'APP VERSION',stepRepo:'LATEST MAIN',stepDeploy:'DEPLOYMENT',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCESS COMPLETE',sync:'Last',clearing:'Clearing cache...',cleared:'Cache cleared',versionInfo:'VERSION INFORMATION'},
    cs:{ready:'Připraveno ke kontrole aktualizací',smooth:'Ukazatel postupu běží plynule od 0 do 100%',checking:'Kontrola internetového připojení...',version:'Načítání nainstalované verze...',repo:'Kontrola nejnovější verze na GitHubu...',deploy:'Kontrola nasazení GitHub Pages...',worker:'Kontrola mechanismu aktualizace...',cache:'Kontrola mezipaměti...',done:'Kontrola aktualizace dokončena',ok:'VŠE OK',need:'AKTUALIZACE',offline:'BEZ INTERNETU',browser:'PROHLÍŽEČ',pwa:'PWA',auto:'AUTOMATICKÉ',manual:'RUČNÍ',stepReady:'SYSTÉM PŘIPRAVEN',waiting:'Čekání na spuštění',stepNet:'SÍŤ',stepVersion:'VERZE APLIKACE',stepRepo:'NEJNOVĚJŠÍ MAIN',stepDeploy:'NASAZENÍ',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCES DOKONČEN',sync:'Poslední',clearing:'Čištění mezipaměti...',cleared:'Mezipaměť vyčištěna',versionInfo:'INFORMACE O VERZI'},
    da:{ready:'Klar til at søge efter opdateringer',smooth:'Statusindikatoren går jævnt fra 0 til 100%',checking:'Kontrollerer internetforbindelse...',version:'Læser installeret version...',repo:'Kontrollerer seneste GitHub-version...',deploy:'Kontrollerer GitHub Pages-udrulning...',worker:'Kontrollerer browseropdatering...',cache:'Kontrollerer cache...',done:'Opdateringskontrol afsluttet',ok:'ALT OK',need:'OPDATERING',offline:'INTET INTERNET',browser:'BROWSER',pwa:'PWA',auto:'AUTOMATISK',manual:'MANUEL',stepReady:'SYSTEM KLAR',waiting:'Venter på start',stepNet:'NETVÆRK',stepVersion:'APPVERSION',stepRepo:'SENESTE MAIN',stepDeploy:'UDRULNING',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCES FÆRDIG',sync:'Senest',clearing:'Rydder cache...',cleared:'Cache ryddet',versionInfo:'VERSIONSOPLYSNINGER'},
    de:{ready:'Bereit zur Update-Prüfung',smooth:'Fortschrittsanzeige läuft von 0 bis 100%',checking:'Internetverbindung wird geprüft...',version:'Installierte Version wird gelesen...',repo:'Neueste GitHub-Version wird geprüft...',deploy:'GitHub-Pages-Bereitstellung wird geprüft...',worker:'Browser-Update-Mechanismus wird geprüft...',cache:'Cache wird geprüft...',done:'Update-Prüfung abgeschlossen',ok:'ALLES OK',need:'UPDATE',offline:'KEIN INTERNET',browser:'BROWSER',pwa:'PWA',auto:'AUTOMATISCH',manual:'MANUELL',stepReady:'SYSTEM BEREIT',waiting:'Warten auf Start',stepNet:'NETZWERK',stepVersion:'APP-VERSION',stepRepo:'NEUESTER MAIN',stepDeploy:'BEREITSTELLUNG',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROZESS BEENDET',sync:'Zuletzt',clearing:'Cache wird geleert...',cleared:'Cache geleert',versionInfo:'VERSIONSINFORMATIONEN'},
    no:{ready:'Klar til å se etter oppdateringer',smooth:'Fremdriftsindikatoren går jevnt fra 0 til 100%',checking:'Kontrollerer internettforbindelse...',version:'Leser installert versjon...',repo:'Kontrollerer siste GitHub-versjon...',deploy:'Kontrollerer GitHub Pages-distribusjon...',worker:'Kontrollerer nettleseroppdatering...',cache:'Kontrollerer hurtigbuffer...',done:'Oppdateringskontroll fullført',ok:'ALT OK',need:'OPPDATERING',offline:'INGEN INTERNETT',browser:'NETTLESER',pwa:'PWA',auto:'AUTOMATISK',manual:'MANUELL',stepReady:'SYSTEM KLART',waiting:'Venter på start',stepNet:'NETTVERK',stepVersion:'APPVERSJON',stepRepo:'SISTE MAIN',stepDeploy:'DISTRIBUSJON',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROSESS FULLFØRT',sync:'Sist',clearing:'Tømmer cache...',cleared:'Cache tømt',versionInfo:'VERSJONSINFORMASJON'},
    fr:{ready:'Prêt à rechercher les mises à jour',smooth:'La progression fonctionne de 0 à 100%',checking:'Vérification de la connexion Internet...',version:'Lecture de la version installée...',repo:'Vérification de la dernière version GitHub...',deploy:'Contrôle du déploiement GitHub Pages...',worker:'Contrôle du mécanisme de mise à jour...',cache:'Contrôle du cache...',done:'Contrôle de mise à jour terminé',ok:'TOUT EST OK',need:'MISE À JOUR',offline:'PAS D’INTERNET',browser:'NAVIGATEUR',pwa:'PWA',auto:'AUTOMATIQUE',manual:'MANUEL',stepReady:'SYSTÈME PRÊT',waiting:'En attente de démarrage',stepNet:'RÉSEAU',stepVersion:'VERSION APP',stepRepo:'DERNIER MAIN',stepDeploy:'DÉPLOIEMENT',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCESSUS TERMINÉ',sync:'Dernière',clearing:'Nettoyage du cache...',cleared:'Cache nettoyé',versionInfo:'INFORMATIONS DE VERSION'},
    ro:{ready:'Gata pentru verificarea actualizărilor',smooth:'Indicatorul progresează de la 0 la 100%',checking:'Verificare conexiune la Internet...',version:'Citire versiune instalată...',repo:'Verificare ultima versiune GitHub...',deploy:'Control implementare GitHub Pages...',worker:'Control mecanism actualizare browser...',cache:'Verificare cache...',done:'Verificarea actualizării s-a încheiat',ok:'TOTUL OK',need:'ACTUALIZARE',offline:'FĂRĂ INTERNET',browser:'BROWSER',pwa:'PWA',auto:'AUTOMAT',manual:'MANUAL',stepReady:'SISTEM GATA',waiting:'Așteptare pornire',stepNet:'REȚEA',stepVersion:'VERSIUNE APLICAȚIE',stepRepo:'ULTIMUL MAIN',stepDeploy:'IMPLEMENTARE',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCES ÎNCHEIAT',sync:'Ultima',clearing:'Curățare cache...',cleared:'Cache curățat',versionInfo:'INFORMAȚII VERSIUNE'},
    tr:{ready:'Güncellemeleri denetlemeye hazır',smooth:'İlerleme göstergesi 0’dan 100’e çalışır',checking:'İnternet bağlantısı kontrol ediliyor...',version:'Yüklü sürüm okunuyor...',repo:'En son GitHub sürümü kontrol ediliyor...',deploy:'GitHub Pages dağıtımı kontrol ediliyor...',worker:'Tarayıcı güncelleme mekanizması kontrol ediliyor...',cache:'Önbellek kontrol ediliyor...',done:'Güncelleme kontrolü tamamlandı',ok:'HER ŞEY TAMAM',need:'GÜNCELLEME',offline:'İNTERNET YOK',browser:'TARAYICI',pwa:'PWA',auto:'OTOMATİK',manual:'MANUEL',stepReady:'SİSTEM HAZIR',waiting:'Başlatma bekleniyor',stepNet:'AĞ',stepVersion:'UYGULAMA SÜRÜMÜ',stepRepo:'EN YENİ MAIN',stepDeploy:'DAĞITIM',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'İŞLEM TAMAMLANDI',sync:'Son',clearing:'Önbellek temizleniyor...',cleared:'Önbellek temizlendi',versionInfo:'SÜRÜM BİLGİLERİ'},
    it:{ready:'Pronto per verificare gli aggiornamenti',smooth:'La barra di avanzamento va da 0 a 100%',checking:'Controllo connessione Internet...',version:'Lettura versione installata...',repo:'Controllo ultima versione GitHub...',deploy:'Controllo distribuzione GitHub Pages...',worker:'Controllo meccanismo aggiornamento browser...',cache:'Controllo cache...',done:'Controllo aggiornamento completato',ok:'TUTTO OK',need:'AGGIORNAMENTO',offline:'NESSUN INTERNET',browser:'BROWSER',pwa:'PWA',auto:'AUTOMATICO',manual:'MANUALE',stepReady:'SISTEMA PRONTO',waiting:'In attesa di avvio',stepNet:'RETE',stepVersion:'VERSIONE APP',stepRepo:'ULTIMO MAIN',stepDeploy:'DISTRIBUZIONE',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCESSO COMPLETATO',sync:'Ultima',clearing:'Pulizia cache...',cleared:'Cache pulita',versionInfo:'INFORMAZIONI VERSIONE'},
    nl:{ready:'Klaar om op updates te controleren',smooth:'Voortgang loopt vloeiend van 0 tot 100%',checking:'Internetverbinding controleren...',version:'Geïnstalleerde versie lezen...',repo:'Nieuwste GitHub-versie controleren...',deploy:'GitHub Pages-uitrol controleren...',worker:'Browserupdate-mechanisme controleren...',cache:'Cache controleren...',done:'Updatecontrole voltooid',ok:'ALLES OK',need:'UPDATE',offline:'GEEN INTERNET',browser:'BROWSER',pwa:'PWA',auto:'AUTOMATISCH',manual:'HANDMATIG',stepReady:'SYSTEEM GEREED',waiting:'Wachten op start',stepNet:'NETWERK',stepVersion:'APPVERSIE',stepRepo:'NIEUWSTE MAIN',stepDeploy:'UITROL',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'PROCES VOLTOOID',sync:'Laatste',clearing:'Cache wissen...',cleared:'Cache gewist',versionInfo:'VERSIE-INFORMATIE'},
    uk:{ready:'Готово до перевірки оновлень',smooth:'Індикатор прогресу працює від 0 до 100%',checking:'Перевірка Інтернет-з’єднання...',version:'Читання встановленої версії...',repo:'Перевірка останньої версії GitHub...',deploy:'Перевірка розгортання GitHub Pages...',worker:'Перевірка механізму оновлення браузера...',cache:'Перевірка кешу...',done:'Перевірку оновлення завершено',ok:'УСЕ ГАРАЗД',need:'ОНОВЛЕННЯ',offline:'НЕМАЄ ІНТЕРНЕТУ',browser:'БРАУЗЕР',pwa:'PWA',auto:'АВТОМАТИЧНО',manual:'ВРУЧНУ',stepReady:'СИСТЕМА ГОТОВА',waiting:'Очікування запуску',stepNet:'МЕРЕЖА',stepVersion:'ВЕРСІЯ ЗАСТОСУНКУ',stepRepo:'ОСТАННІЙ MAIN',stepDeploy:'РОЗГОРТАННЯ',stepWorker:'SERVICE WORKER',stepCache:'CACHE',stepDone:'ПРОЦЕС ЗАВЕРШЕНО',sync:'Остання',clearing:'Очищення кешу...',cleared:'Кеш очищено',versionInfo:'ІНФОРМАЦІЯ ПРО ВЕРСІЮ'}
  };
  const T=L[lang]||L.pl;
  let running=false, pct=0, startedAt=0, versionData={}, latestCommit=null, latestRun=null;
  const els={fill:$('#progressFill'),glow:$('#progressGlow'),pct:$('#progressPct'),title:$('#processTitle'),detail:$('#processDetail'),step:$('#stepName'),stepDetail:$('#stepDetail'),eta:$('#etaValue'),version:$('#installedVersion'),build:$('#installedBuild'),mode:$('#installMode'),updateMode:$('#updateMode'),state:$('#systemState'),lastSync:$('#lastSyncText'),sync:$('#syncTopVisual'),dialog:$('#versionDialog'),dialogTitle:$('#versionDialogTitle'),dialogBody:$('#versionDialogBody')};
  const fmtDate=d=>new Intl.DateTimeFormat(lang==='en'?'en-GB':lang,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d);
  const short=s=>s?String(s).slice(0,12):'—';
  async function fetchJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
  function setProgress(v){pct=Math.max(0,Math.min(100,Math.round(v)));const w=486*pct/100;els.fill.setAttribute('width',String(w));els.glow.setAttribute('cx',String(51+w));els.pct.textContent=pct+'%';}
  function setStage(p,title,detail,step,stepDetail){setProgress(p);els.title.textContent=title;els.detail.textContent=detail;els.step.textContent=step;els.stepDetail.textContent=stepDetail||detail;const e=Math.max(0,(performance.now()-startedAt)/1000);const remaining=p>0&&p<100?Math.max(0,Math.round(e*(100-p)/p)):0;els.eta.textContent=`00:${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;}
  function showLastSync(){const raw=localStorage.getItem('crm.settings.lastSync');els.lastSync.textContent=T.sync+': '+(raw?fmtDate(new Date(raw)):'—');}
  async function networkProbe(){if(!navigator.onLine)return false;try{const r=await fetch('./?update-health='+Date.now(),{method:'HEAD',cache:'no-store'});return r.ok}catch(_){return false}}
  async function detectMode(){const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;els.mode.textContent=standalone?T.pwa:T.browser;const regs='serviceWorker'in navigator?await navigator.serviceWorker.getRegistrations().catch(()=>[]):[];els.updateMode.textContent=regs.length?T.auto:T.manual;return regs;}
  async function runUpdateCheck(){
    if(running)return;running=true;startedAt=performance.now();els.sync.classList.add('syncing');setProgress(0);
    try{
      setStage(5,T.checking,T.smooth,T.stepNet,T.checking);await sleep(180);const online=await networkProbe();if(!online)throw new Error(T.offline);setStage(15,T.checking,'ONLINE',T.stepNet,'ONLINE');await sleep(160);
      setStage(24,T.version,T.smooth,T.stepVersion,T.version);versionData=await fetchJson('./version.json?ts='+Date.now());els.version.textContent=versionData.version||'—';els.build.textContent=(versionData.build?('BUILD '+versionData.build):'')+(versionData.deployed_commit?(' • '+short(versionData.deployed_commit)):'');await sleep(180);
      setStage(40,T.repo,T.smooth,T.stepRepo,T.repo);latestCommit=await fetchJson(API+'/commits/main?ts='+Date.now());await sleep(180);
      setStage(58,T.deploy,T.smooth,T.stepDeploy,T.deploy);const runs=await fetchJson(API+'/actions/runs?branch=main&per_page=12&ts='+Date.now());latestRun=(runs.workflow_runs||[]).find(r=>r.conclusion==='success')||null;await sleep(180);
      setStage(76,T.worker,T.smooth,T.stepWorker,T.worker);const regs=await detectMode();for(const reg of regs){try{await reg.update()}catch(_){}}await sleep(180);
      setStage(90,T.cache,T.smooth,T.stepCache,T.cache);if('caches'in window){await caches.keys().catch(()=>[])}await sleep(180);
      const current=Boolean(latestRun&&latestCommit&&latestRun.head_sha===latestCommit.sha);els.state.textContent=current?T.ok:T.need;els.state.classList.toggle('warn',!current);setStage(100,T.done,current?T.ok:T.need,T.stepDone,current?T.ok:T.need);els.eta.textContent='00:00:00';localStorage.setItem('crm.settings.lastSync',new Date().toISOString());showLastSync();
    }catch(e){els.state.textContent=T.offline;els.state.classList.add('warn');setStage(Math.max(pct,10),String(e.message||e),T.offline,T.stepNet,T.offline)}finally{els.sync.classList.remove('syncing');running=false;}
  }
  async function clearCache(){if(running)return;running=true;startedAt=performance.now();els.sync.classList.add('syncing');try{setStage(5,T.clearing,T.smooth,T.stepCache,T.clearing);const keys='caches'in window?await caches.keys():[];let done=0;for(const key of keys){await caches.delete(key);done++;setStage(10+Math.round((done/Math.max(1,keys.length))*80),T.clearing,key,T.stepCache,`${done} / ${keys.length}`);await sleep(120)}setStage(100,T.cleared,T.cleared,T.stepDone,T.cleared);els.eta.textContent='00:00:00'}finally{els.sync.classList.remove('syncing');running=false}}
  function openVersion(){const body={language:lang,installed:versionData,latest_main:latestCommit?{sha:latestCommit.sha,message:latestCommit.commit?.message,date:latestCommit.commit?.committer?.date}:null,last_successful_deployment:latestRun?{head_sha:latestRun.head_sha,run_number:latestRun.run_number,updated_at:latestRun.updated_at}:null,last_sync:localStorage.getItem('crm.settings.lastSync')};els.dialogTitle.textContent=T.versionInfo;els.dialogBody.textContent=JSON.stringify(body,null,2);els.dialog.showModal();}
  function init(){document.documentElement.lang=lang;showLastSync();els.title.textContent=T.ready;els.detail.textContent=T.smooth;els.step.textContent=T.stepReady;els.stepDetail.textContent=T.waiting;els.dialogTitle.textContent=T.versionInfo;detectMode();setProgress(0);document.querySelector('[data-action="sync"]').addEventListener('click',runUpdateCheck);document.querySelector('[data-action="check"]').addEventListener('click',runUpdateCheck);document.querySelector('[data-action="version"]').addEventListener('click',openVersion);document.querySelector('[data-action="cache"]').addEventListener('click',clearCache);document.querySelector('[data-action="pulpit"]').addEventListener('click',()=>location.href='./');$('#closeVersion').addEventListener('click',()=>els.dialog.close());if(new URLSearchParams(location.search).get('debug')==='1')$('#updateStage').classList.add('debug');}
  init();
})();
